# Generated by Django 2.2.7 on 2019-11-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('isBorrowed', models.BooleanField(default=False)),
                ('isBroken', models.BooleanField(default=False)),
                ('password', models.CharField(default='0000', max_length=4)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.User')),
            ],
        ),
    ]
